version: '3'

networks: 
  laravel:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8001"
    volumes: 
      - ./src:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - db
      - phpmyadmin
    networks: 
      - laravel
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial
    ports:  
      - "3306:3306"
    networks: 
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "9999:80"
    depends_on:
      - db
    networks: 
      - laravel
  php:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes: 
      - ./src:/var/www/app
    ports: 
      - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
    networks: 
      - laravel